# [Info]
site_name: FZU飞跃手册 # 左上角标题
site_url: https://fzu-fly.online
site_author: FZU飞跃手册编委会
site_description: FZU-flying-book
## [top-right corner]
repo_url: https://github.com/MIECer/FZU-flying-book # 右上角点击跳转的链接
repo_name: FZU-flying-book # 右上角的名字

# ======================================================

# [Navigtion] 左侧文章导航
nav:
  # - index.md
  - 关于本站:
    - about/index.md
    - 本站致谢: about/thanks.md
    - 主编作者: about/people.md


# ——————————————————————————————————————————————————————

  - 加入创作:
    - join/index.md


# ——————————————————————————————————————————————————————

  - 飞跃重洋:
    - flying/index.md
    - 准备工作:
      - 信息搜索:
        - 英国留学信息搜索: flying/prepare/common/uk-info.md
      - 信息科普:
        - 欧陆留学科普帖: flying/prepare/common/eu-common-wzr.md
    - 英港新: 
      - 英港新数据总览: flying/uk-hk.md
      - 英国案例:
        - Cambridge EECS @23fall: flying/hk/2023/temp.md
      - 港新案例:
        - HKUST SE @23fall: flying/uk/2023/temp.md
    - 北美:
      - 北美数据总览: flying/na.md
      - 北美案例:
        - MIT Robotics @23fall: flying/na/2023/temp.md
    - 欧洲:
      - 欧洲数据总览: flying/eu.md
      - 申请案例:
        - ETH 自动化 @23fall: flying/eu/2023/temp.md
    - 亚洲:
      - 亚洲数据总览: flying/jk.md
      - 新加坡案例:
        - 东京工业大学 控制 @23fall: flying/jk/2023/temp.md
      - 日本案例:
        - 东京工业大学 控制 @23fall: flying/jk/2023/temp.md
      - 韩国案例:
        - 东京工业大学 控制 @23fall: flying/jk/2023/temp.md
      - 香港案例:
        - 东京工业大学 控制 @23fall: flying/jk/2023/temp.md
    

# # ——————————————————————————————————————————————————————

#   - 英港新:
#     # - 
#     - 英港新数据总览: flying/uk-hk.md
#     - 英国案例:
#       - Cambridge EECS @23fall: flying/hk/2023/temp.md
#     - 港新案例:
#       - HKUST SE @23fall: flying/uk/2023/temp.md

# # ——————————————————————————————————————————————————————

#   - 北美:
#     # - 
#     - 北美数据总览: flying/na.md
#     - 北美案例:
#       - MIT Robotics @23fall: flying/na/2023/temp.md

# # ——————————————————————————————————————————————————————

#   - 欧洲:
#     - 欧洲数据总览: flying/eu.md
#     - 申请案例:
#       - ETH 自动化 @23fall: flying/eu/2023/temp.md

# # ——————————————————————————————————————————————————————

#   - 亚洲:
#     - 日韩数据总览: flying/jk.md
#     - 申请案例:
#       - 东京工业大学 控制 @23fall: flying/jk/2023/temp.md


# ——————————————————————————————————————————————————————

  - 国内升研:
    - sprint/index.md
    - 关于保研: sprint/baoyan/index.md

    - 关于考研: sprint/kaoyan/index.md


# ——————————————————————————————————————————————————————

  - 实习就业:
    - work/index.md
    - 大三实习学期:
      - work/intern/intern.md
    - 秋招包裹分享:
      - work/package/index.md
      - 2023秋招: 
        - 星网锐捷12k 15薪: work/package/2023/temp.md

# ——————————————————————————————————————————————————————

  - 修读指北:
    - learning/index.md
    - MIEC专业课: learning/miec-gpa/index.md

    - FZU公共课: learning/public/index.md

    - 关于竞赛: learning/competition/index.md

    - 关于科研: learning/lab/index.md

# ——————————————————————————————————————————————————————

  - 自由评论:
    - comment/index.md
    - 评论区: comment/c.md
    

# ——————————————————————————————————————————————————————

  - 特别致谢©:
    - advertising/index.md


# ======================================================

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.path #
    - navigation.top #
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon: # 'clound' 右上角图标的另一种样式，需要注释下行
    repo: fontawesome/brands/github
  custom_dir: overrides
edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [bottom-left corner]
copyright: © 2023 FZU-MIECer Copyleft # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/MIECer/FZU-flying-book
      name: GitHub | FZU-flying-book
    - icon: fontawesome/brands/docker
      link: https://caihanlin.com/
      name: Website | HanlinCAI
    # - icon: fontawesome/brands/twitter
      # link: https://twitter.com/lancecai2002
      # name: Twitter | lancecai2002
    # - icon: fontawesome/brands/bilibili
      # link: https://space.bilibili.com/594030035
      # name: Bilibili | Lance Cai # 鼠标悬浮提示
    # - icon: fontawesome/brands/linkedin
      # link: https://www.linkedin.com/in/hanlin-cai-07b53b23b/
      # name: Linkedin | hanlin-cai # 鼠标悬浮提示
    
# ======================================================

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - attach/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  # - attach/css/no-footer.css # 不使用底部的翻页
  - attach/css/unordered-list-symbols.css # multiplt unordered list symbols

google_analytics: 
  - 'UA-35232574'
  - 'auto'


# Lastly Update by Hanlin CAI in 2023/06/09.